fix Audio.play_sound with volume (#43)
I'm not sure where this issue lies. 

I'm not sure if this is a bug in 9.4.2.0 that surfaced because
Audio.playSound recently got a new overloaded method?

So two overloaded java methods with the same number of parameters, but
different signatures.

I am calling the java method with `Audio.playSound(nil, "soundfile",
PercentType.new(100))`

It is supposed to call this:
https://www.openhab.org/javadoc/latest/org/openhab/core/model/script/actions/audio#playSound(java.lang.String,java.lang.String,org.openhab.core.library.types.PercentType)

but instead I got an error indicating that it's trying to call this

https://www.openhab.org/javadoc/latest/org/openhab/core/model/script/actions/audio#playSound(java.lang.String,java.lang.String,float)

This is the error/exception from my log:
`for method Audio.playSound expected
[java.lang.String,java.lang.String,float]; got:
[null,java.lang.String,org.openhab.core.library.types.PercentType];
error: null (TypeError)`

When I call the method with a String as the first argument, it would
work fine.

So this PR is a workaround to help jruby/java find the correct method.

Signed-off-by: Jimmy Tanagra <jcode@tanagra.id.au>